name: cometapp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - flask=1.1.*
  - folium=0.10.1
  - numpy=1.18*
  - pandas=1.0.*
  - pip=20.0.*
  - sqlalchemy=1.3.*
  - passlib=1.7.*
  - pip:
    - flask-mail==0.9.*
    - wtforms==2.2.*
