name: cometapp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2_cffi=19.1.*
  - asn1crypto=1.3.*
  - bcrypt=3.1.*
  - blas=1.0
  - branca=0.3.*
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.*
  - click=7.0
  - cryptography=2.8
  - flask=1.1.*
  - folium=0.10.1
  - idna=2.8
  - itsdangerous=1.1.*
  - jinja2=2.11.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.*
  - libgcc-ng=9.1.*
  - libgfortran-ng=7.3.*
  - libopenblas=0.3.*
  - libstdcxx-ng=9.1.*
  - markupsafe=1.1.*
  - ncurses=6.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.*
  - passlib=1.7.*
  - pip=20.0.*
  - pycparser=2.19
  - pyopenssl=19.1.*
  - pysocks=1.7.*
  - python=3.8.*
  - python-dateutil=2.8.*
  - pytz=2019.3
  - readline=7.0
  - requests=2.22.0
  - setuptools=45.1.*
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.*
  - urllib3=1.25.7
  - vincent=0.4.*
  - werkzeug=0.16.1
  - wheel=0.34.2
  - xz=5.2.*
  - zlib=1.2.11
  - pip:
    - blinker==1.4
    - flask-mail==0.9.*
    - wtforms==2.2.*
